### ISSUE TITLE
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /workdir/convert_path/onnx/oriented_rcnn_r50_fpn_1x_dota_le90-fp32/end2end.onnx failed:Fatal error: TRTBatchedNMS is not a registered function/op

### ISSUE THREAD

**Issue by Worromots** [open-mmlab/mmdeploy#2388]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [x] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

I tried to test an ONNX model using `tools.py/test.py`, but encountered an error. I tried the following operations, but the problem was not solved: setting the environment variable `export LD_PRELOAD=/build/lib/libmmdeploy_tensorrt_ops.so`, setting the environment variable `export LD_LIBRARY_PATH=/workdir/build/lib:$LD_LIBRARY_PATH`.

### Reproduction

python tools/deploy.py \
    configs/mmrotate/rotated-detection_onnxruntime_dynamic.py \
    rotated-faster-rcnn-le90_r50_fpn_1x_dota.py \
    rotated_faster_rcnn_r50_fpn_1x_dota_le90-0393aa5c.pth \
    dota_demo.jpg \
    --work-dir mmdeploy_models/mmrotate/ort \
    --device cpu \
    --show \
    --dump-info

### Environment

```Shell
2023-08-30 17:40:49,386 - mmdeploy - INFO - 

2023-08-30 17:40:49,386 - mmdeploy - INFO - **********Environmental information**********
fatal: Not a git repository (or any parent up to mount point /workdir)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2023-08-30 17:40:49,733 - mmdeploy - INFO - sys.platform: linux
2023-08-30 17:40:49,733 - mmdeploy - INFO - Python: 3.9.16 (main, Jun 28 2023, 20:02:54) [GCC 8.3.1 20190311 (Red Hat 8.3.1-3)]
2023-08-30 17:40:49,733 - mmdeploy - INFO - CUDA available: True
2023-08-30 17:40:49,733 - mmdeploy - INFO - GPU 0: Tesla V100-PCIE-16GB
2023-08-30 17:40:49,733 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda
2023-08-30 17:40:49,733 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.4, V11.4.152
2023-08-30 17:40:49,733 - mmdeploy - INFO - GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
2023-08-30 17:40:49,733 - mmdeploy - INFO - PyTorch: 1.10.0a0+git5aede98
2023-08-30 17:40:49,733 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 8.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2018.0.1 Product Build 20171007 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.4
  - NVCC architecture flags: -gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80
  - CuDNN 8.8  (built against CUDA 11.8)
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.4, CUDNN_VERSION=8.8.0, CXX_COMPILER=/opt/rh/devtoolset-8/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

2023-08-30 17:40:49,733 - mmdeploy - INFO - TorchVision: 0.11.0a0+58a60b2
2023-08-30 17:40:49,734 - mmdeploy - INFO - OpenCV: 4.7.0
2023-08-30 17:40:49,734 - mmdeploy - INFO - MMCV: 1.7.0
2023-08-30 17:40:49,734 - mmdeploy - INFO - MMCV Compiler: GCC 7.3
2023-08-30 17:40:49,734 - mmdeploy - INFO - MMCV CUDA Compiler: 11.4
2023-08-30 17:40:49,734 - mmdeploy - INFO - MMDeploy: 0.10.0+
2023-08-30 17:40:49,734 - mmdeploy - INFO - 

2023-08-30 17:40:49,734 - mmdeploy - INFO - **********Backend information**********
2023-08-30 17:40:50,430 - mmdeploy - INFO - onnxruntime: 1.10.0 ops_is_avaliable : False
2023-08-30 17:40:50,474 - mmdeploy - INFO - tensorrt: 8.5.3.1   ops_is_avaliable : True
2023-08-30 17:40:50,502 - mmdeploy - INFO - ncnn: None  ops_is_avaliable : False
2023-08-30 17:40:50,503 - mmdeploy - INFO - pplnn_is_avaliable: False
2023-08-30 17:40:50,506 - mmdeploy - INFO - openvino_is_avaliable: False
2023-08-30 17:40:50,531 - mmdeploy - INFO - snpe_is_available: False
2023-08-30 17:40:50,533 - mmdeploy - INFO - ascend_is_available: False
2023-08-30 17:40:50,535 - mmdeploy - INFO - coreml_is_available: False
2023-08-30 17:40:50,535 - mmdeploy - INFO - 

2023-08-30 17:40:50,535 - mmdeploy - INFO - **********Codebase information**********
2023-08-30 17:40:52,286 - mmdeploy - INFO - mmdet:      2.28.2
2023-08-30 17:40:52,286 - mmdeploy - INFO - mmseg:      None
2023-08-30 17:40:52,286 - mmdeploy - INFO - mmcls:      None
```

**Comment by RunningLeon** [comment]
@BUAA-Worromot hi, if you run the command, the produced end2end.onnx does not have `TRTBatchedNMS`. Have you changed any thin in `configs/mmrotate/rotated-detection_onnxruntime_dynamic.py`. BTW, according to `2023-08-30 17:40:50,430 - mmdeploy - INFO - onnxruntime: 1.10.0 ops_is_avaliable : False`, you have not built mmdeploy with onnxruntime custom ops.
```
python tools/deploy.py \
configs/mmrotate/rotated-detection_onnxruntime_dynamic.py \
rotated-faster-rcnn-le90_r50_fpn_1x_dota.py \
rotated_faster_rcnn_r50_fpn_1x_dota_le90-0393aa5c.pth \
dota_demo.jpg \
--work-dir mmdeploy_models/mmrotate/ort \
--device cpu \
--show \
--dump-info
```

**Comment by BUAA-Worromot** [comment]
Thank you for your prompt reply. I did make some modifications to `rotated-detection_onnxruntime_dynamic.py`, and the problem was solved when I used the original `rotated-detection_onnxruntime_dynamic.py` for conversion. However, I encountered another problem during the conversion to TRT model, where the precision of two models decreased significantly after conversion, while the precision of the other two models was aligned.
<img width="1338" alt="image" src="https://github.com/open-mmlab/mmdeploy/assets/49706682/70ab906a-6f21-4ddc-a0b6-07c61ee11e5c">
this is the command I used to convert pth to trt
`python3 tools/torch2onnx.py ${convert_config} ${train_config} $checkpoint $img --work-dir ${convert_path} --device=cuda:0
  /usr/local/TensorRT-8.2.0.6/bin/trtexec --onnx=$onnx_path $input_io_format $fp16_mode --saveEngine=$trt_path \
    --plugins=/workdir/infra-mt-cvzoo-converter/build/lib/libmmdeploy_tensorrt_ops.so \
    --minShapes=$min_shape \
    --optShapes=$opt_shape \
    --maxShapes=$max_shape \
    --workspace=$workspace
`

**Comment by RunningLeon** [comment]
hi, 
1. ROI_Trans is not supported by https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmrotate.html#supported-models
2. There might be something wrong with Oriented RCNN, could you check if onnxruntime is aligned with PyTorch?

**Comment by Worromots** [comment]
Hi, 
1. I am using 0.3.4 mmdploy, ROI_Trans is support by [https://mmdeploy.readthedocs.io/en/0.x/04-supported-codebases/mmrotate.html]
2. I tried to evaluation the onnx model on GPU, but I got an error:
> /usr/local/anaconda3/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:56: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'CPUExecutionProvider'
  "Available providers: '{}'".format(name, ", ".join(available_provider_names))
[                                                  ] 0/3066, elapsed: 0s, ETA:Traceback (most recent call last):
  File "/workdir/infra-mt-cvzoo-converter/tools/test.py", line 157, in <module>
    main()
  File "/workdir/infra-mt-cvzoo-converter/tools/test.py", line 148, in main
    args.show_dir)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/mmdeploy/codebase/base/task.py", line 141, in single_gpu_test
    out_dir, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/mmdeploy/codebase/mmrotate/deploy/mmrotate.py", line 156, in single_gpu_test
    outputs = single_gpu_test(model, data_loader, show, out_dir, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/mmdet/apis/test.py", line 29, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 51, in forward
    return super().forward(*inputs, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/mmdeploy/codebase/mmrotate/deploy/rotated_detection_model.py", line 120, in forward
    outputs = self.forward_test(input_img, img_metas, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/mmdeploy/codebase/mmrotate/deploy/rotated_detection_model.py", line 158, in forward_test
    outputs = self.wrapper({self.input_name: imgs})
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/mmdeploy/backend/onnxruntime/wrapper.py", line 98, in forward
    buffer_ptr=input_tensor.data_ptr())
  File "/usr/local/anaconda3/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 478, in bind_input
    buffer_ptr,
RuntimeError: Error when binding input: There's no data transfer registered for copying tensors from Device:[DeviceType:1 MemoryType:0 DeviceId:0] to Device:[DeviceType:0 MemoryType:0 DeviceId:0]

**Comment by RunningLeon** [comment]
hi， 
1. you are using mmdeploy==0.3.0? you should try with the latest released version or `main` branch.
2. could you use `cuda:0` for all commands?

**Comment by Worromots** [comment]
Hi, thanks for your patient reply。
1. my project is developed based on  mmdeploy==0.3.4, I can not understand the significant loss of mAP, because the official  document shows ROI_Trans is supported.
2. I just tried convert pth to onnx using cuda:0, and evaluate the onnx on cuda:0, but still get the same error. 
3. I tried to re-build mmdeploy to get libmmdeploy_onnxruntime_ops.so following https://mmdeploy.readthedocs.io/en/0.x/01-how-to-build/linux-x86_64.html but failed with error:
> error: the value of ‘mmdeploy::__domain_mmdeployMMCVModulatedDeformConvOp’ is not usable in a constant expression
when execute `make -j5`. Then I found a pre-build  libmmdeploy_onnxruntime_ops.so  and export the path to LD_LIBRARY_PATH, and evaluate the onnx model on cuda:0 but still got the same error:
> RuntimeError: Error when binding input: There's no data transfer registered for copying tensors from Device:[DeviceType:1 MemoryType:0 DeviceId:0] to Device:[DeviceType:0 MemoryType:0 DeviceId:0]
I run check_env.py to check environment and got these info:

> 2023-08-31 15:46:54,690 - mmdeploy - INFO - 

2023-08-31 15:46:54,691 - mmdeploy - INFO - **********Environmental information**********
/bin/sh: /usr/local/anaconda3/lib/libuuid.so.1: no version information available (required by /opt/meituan/dolphinfs-client-preload/libdolphinfs_client_preload.so)
/usr/local/cuda/bin/nvcc: /usr/local/anaconda3/lib/libuuid.so.1: no version information available (required by /opt/meituan/dolphinfs-client-preload/libdolphinfs_client_preload.so)
/bin/sh: /usr/local/anaconda3/lib/libuuid.so.1: no version information available (required by /opt/meituan/dolphinfs-client-preload/libdolphinfs_client_preload.so)
gcc: /usr/local/anaconda3/lib/libuuid.so.1: no version information available (required by /opt/meituan/dolphinfs-client-preload/libdolphinfs_client_preload.so)
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2023-08-31 15:46:54,958 - mmdeploy - INFO - sys.platform: linux
2023-08-31 15:46:54,958 - mmdeploy - INFO - Python: 3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
2023-08-31 15:46:54,958 - mmdeploy - INFO - CUDA available: True
2023-08-31 15:46:54,958 - mmdeploy - INFO - GPU 0,1: Tesla V100-PCIE-16GB
2023-08-31 15:46:54,958 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda
2023-08-31 15:46:54,958 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.0, V11.0.221
2023-08-31 15:46:54,958 - mmdeploy - INFO - GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
2023-08-31 15:46:54,958 - mmdeploy - INFO - PyTorch: 1.10.0+cu113
2023-08-31 15:46:54,959 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

2023-08-31 15:46:54,959 - mmdeploy - INFO - TorchVision: 0.11.0+cu113
2023-08-31 15:46:54,959 - mmdeploy - INFO - OpenCV: 4.6.0
2023-08-31 15:46:54,959 - mmdeploy - INFO - MMCV: 1.7.0
2023-08-31 15:46:54,959 - mmdeploy - INFO - MMCV Compiler: GCC 9.3
2023-08-31 15:46:54,959 - mmdeploy - INFO - MMCV CUDA Compiler: 11.3
2023-08-31 15:46:54,959 - mmdeploy - INFO - MMDeploy: 0.14.0+
2023-08-31 15:46:54,959 - mmdeploy - INFO - 

2023-08-31 15:46:54,959 - mmdeploy - INFO - **********Backend information**********
Traceback (most recent call last):
  File "infra-mt-cvzoo-converter/tools/check_env.py", line 68, in <module>
    check_backend()
  File "infra-mt-cvzoo-converter/tools/check_env.py", line 27, in check_backend
    logger.info(f'onnxruntime: {ort_version}\tops_is_avaliable : '
AttributeError: module 'mmdeploy.apis.onnxruntime' has no attribute 'is_custom_ops_available'
I think there maybe something wrong with libmmdeploy_onnxruntime_ops.so I found, but I fail to build it by myself as mentioned above.

**Comment by RunningLeon** [comment]
hi, it seems you are using mmdeploy==0.14.0. maybe you can use [docker image](https://hub.docker.com/layers/openmmlab/mmdeploy/ubuntu20.04-cuda11.3-mmdeploy0.14.0/images/sha256-ac1fce42efa5960138ac939b12d946ade792c7436964e6523beec91d5b138a13?context=explore) provided by us.

> 2023-08-31 15:46:54,959 - mmdeploy - INFO - MMDeploy: 0.14.0+
