### ISSUE TITLE
[Bug] failed to get correct rtmdet-ins_m mask result by c++ detector on the CPU

### ISSUE THREAD

**Issue by chuzhixing** [open-mmlab/mmdeploy#2445]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Use the mmdeploy C++SDK to infer the RTMDet Instance model, and the inference backend is onnxruntime. Mask cannot be inferred normally.

Rated issue is `#1849 #1853 #1867 #1884 #1886 #1897`。  
According to `#1849 #1853 #1867`, I used mmdeploy dev1. x (Commit ID=0196cd00) to transform the model, and used the mmdeploy 0. x C++SDK and mmdeploy 1.2.0 C++SDK to infer the transformed model. The inference results of the mask are not correct.  
According to `#1884`, this issue solves the model inference problem on GPU.
Model inference on CPU not resolved?  
According to `#1886 #1897`,Their discussion listed relevant issues.  

Another thing is that mmdeploy 1.2 C++SDK inference for the same RTM instance m model takes longer than mmdeploy 0. x C++SDK inference.
The duration of mmdeploy 1.2 C++SDK is about 1750ms.
The duration of mmdeploy 0. x C++SDK is about 600ms.

### Reproduction

I have tried mmdeploy v1.2.0(Commit ID=71a1e6cc), and mmdeploy dev-1.x(Commit ID=0196cd00)。  
The model conversion command is as follows:  
```shell
cd mmdeploy
python tools/deploy.py \
    configs/mmdet/instance-seg/instance-seg_rtmdet-ins_onnxruntime_static-640x640.py \
    /mmdetection_3.1.0/configs/rtmdet/rtmdet-ins_m_8xb32-300e_coco.py \
    /mmdetection_3.1.0/checkpoints/rtmdet-ins_m_8xb32-300e_coco_20221123_001039-6eba602e.pth \
    /mmdetection_3.1.0/demo/demo.jpg \
    --work-dir mmdeploy_model/ins_m_dynamic \
    --device cpu \
    --log-level INFO \
    --show \
    --dump-info
```
The inference results of the Python versions of the two branches are correct, which can be confirmed through two images.(output_onnxruntime.jpg and output_pytorch.jpg)。

The c++'s code is as follows:
```
#include <iostream>
#include <cstdlib>
#include <opencv2/opencv.hpp>
#include "mmdeploy/detector.hpp"

#include "utils/visualize.h"

int main() {
    const char* device_name = "cpu";
	
    // mmdeploy SDK model，以上文中转出的 faster r-cnn 模型为例
    // std::string model_path = "mmdeploy_model/ins_m_dynamic";
    std::string model_path = "mmdeploy_model/ins_m_dynamic_dev_1.x";
    std::string image_path = "img/demo.jpg";

    // 1. 读取模型
    mmdeploy::Model model(model_path);

    // 2. 创建预测器
    mmdeploy::Detector detector(model, mmdeploy::Device{ device_name });

    auto start = std::chrono::high_resolution_clock::now();  //开始时间

    // 3. 读取图像
    cv::Mat img = cv::imread(image_path);
	
    // 4. 应用预测器推理
    mmdeploy::Detector::Result dets = detector.Apply(img);
	
    // 5. 处理推理结果: 此处我们选择可视化推理结果
    // visualize
    utils::Visualize v;
    v.set_palette(utils::Palette::get("coco"));
    auto sess = v.get_session(img);
    int count = 0;
    float FLAGS_det_thr = 0.3;
    for (const mmdeploy_detection_t& det : dets) {
        if (det.score > FLAGS_det_thr) {  // filter bboxes
            sess.add_det(det.bbox, det.label_id, det.score, det.mask, count++);
        }
    }

    auto stop = std::chrono::high_resolution_clock::now();   //结束时间
    auto duration = std::chrono::duration_cast<std::chrono::microseconds>(stop - start);
    std::cout << "xx时间：" << duration.count() / 1000 << "ms" << std::endl;

    cv::imwrite("output_detection_ins_m_dynamic_04.png", sess.get());
    system("pause");
    return 0;
}
```

The model is RTM instance_m。

The model was transformed by mmdeploy dev 1.x, and the results of using mmdeploy 0.x SDK C++ for inference are as follows:
![dev1 x_mmdeploy_sdk_0 x_rtm_ins_m](https://github.com/open-mmlab/mmdeploy/assets/41979923/b408e927-821a-48ce-b4af-6f7baad454b6)

The model was transformed by mmdeploy dev 1.x, and the results of using mmdeploy1.2.0 SDK C++ for inference are as follows:
![dev1 x_mmdeploy_sdk_1 2 0_rtm_ins_m](https://github.com/open-mmlab/mmdeploy/assets/41979923/59e8d66c-37b8-458e-953e-c7f17a471bf6)

The model was transformed by mmdeploy main 1.2, and the results of using mmdeploy 0.x SDK C++ for inference are as follows:
![main1 2_mmdeploy_sdk_0 x_rtm_ins_m](https://github.com/open-mmlab/mmdeploy/assets/41979923/6febcf1b-4e0d-4c7f-9ab2-987c1125acd2)

The model was transformed by mmdeploy main 1.2, and the results of using mmdeploy1.2.0 SDK C++ for inference are as follows:
![main1 2_mmdeploy_sdk_1 2 0_rtm_ins_m](https://github.com/open-mmlab/mmdeploy/assets/41979923/d2e61532-0413-490c-8609-9f21f12f49c9)

### Environment

```Shell
(openmmlab_3_p38) root@99fa767e7990:/mmdeploy_dev-1.x# python tools/check_env.py 
09/19 13:36:42 - mmengine - INFO - 

09/19 13:36:42 - mmengine - INFO - **********Environmental information**********
09/19 13:36:43 - mmengine - INFO - sys.platform: linux
09/19 13:36:43 - mmengine - INFO - Python: 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
09/19 13:36:43 - mmengine - INFO - CUDA available: True
09/19 13:36:43 - mmengine - INFO - numpy_random_seed: 2147483648
09/19 13:36:43 - mmengine - INFO - GPU 0,1,2,3,4,5,6: NVIDIA TITAN RTX
09/19 13:36:43 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
09/19 13:36:43 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.6, V11.6.55
09/19 13:36:43 - mmengine - INFO - GCC: x86_64-linux-gnu-gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
09/19 13:36:43 - mmengine - INFO - PyTorch: 1.13.1+cu116
09/19 13:36:43 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

09/19 13:36:43 - mmengine - INFO - TorchVision: 0.14.1+cu116
09/19 13:36:43 - mmengine - INFO - OpenCV: 4.8.0
09/19 13:36:43 - mmengine - INFO - MMEngine: 0.8.4
09/19 13:36:43 - mmengine - INFO - MMCV: 2.0.1
09/19 13:36:43 - mmengine - INFO - MMCV Compiler: GCC 9.3
09/19 13:36:43 - mmengine - INFO - MMCV CUDA Compiler: 11.6
09/19 13:36:43 - mmengine - INFO - MMDeploy: 1.2.0+
09/19 13:36:43 - mmengine - INFO - 

09/19 13:36:43 - mmengine - INFO - **********Backend information**********
09/19 13:36:43 - mmengine - INFO - tensorrt:    None
09/19 13:36:44 - mmengine - INFO - ONNXRuntime: 1.15.1
09/19 13:36:44 - mmengine - INFO - ONNXRuntime-gpu:     None
09/19 13:36:44 - mmengine - INFO - ONNXRuntime custom ops:      Available
09/19 13:36:44 - mmengine - INFO - pplnn:       None
09/19 13:36:44 - mmengine - INFO - ncnn:        None
09/19 13:36:44 - mmengine - INFO - snpe:        None
09/19 13:36:44 - mmengine - INFO - openvino:    None
09/19 13:36:44 - mmengine - INFO - torchscript: 1.13.1+cu116
09/19 13:36:44 - mmengine - INFO - torchscript custom ops:      NotAvailable
09/19 13:36:44 - mmengine - INFO - rknn-toolkit:        None
09/19 13:36:44 - mmengine - INFO - rknn-toolkit2:       None
09/19 13:36:44 - mmengine - INFO - ascend:      None
09/19 13:36:44 - mmengine - INFO - coreml:      None
09/19 13:36:44 - mmengine - INFO - tvm: None
09/19 13:36:44 - mmengine - INFO - vacc:        None
09/19 13:36:44 - mmengine - INFO - 

09/19 13:36:44 - mmengine - INFO - **********Codebase information**********
09/19 13:36:44 - mmengine - INFO - mmdet:       3.1.0
09/19 13:36:44 - mmengine - INFO - mmseg:       None
09/19 13:36:44 - mmengine - INFO - mmpretrain:  None
09/19 13:36:44 - mmengine - INFO - mmocr:       None
09/19 13:36:44 - mmengine - INFO - mmagic:      None
09/19 13:36:44 - mmengine - INFO - mmdet3d:     None
09/19 13:36:44 - mmengine - INFO - mmpose:      None
09/19 13:36:44 - mmengine - INFO - mmrotate:    None
09/19 13:36:44 - mmengine - INFO - mmaction:    None
09/19 13:36:44 - mmengine - INFO - mmrazor:     None
09/19 13:36:44 - mmengine - INFO - mmyolo:      None




(openmmlab_3_p38) root@99fa767e7990:/mmdeploy_1.2.0# python tools/check_env.py 
09/19 13:33:55 - mmengine - INFO - 

09/19 13:33:55 - mmengine - INFO - **********Environmental information**********
09/19 13:33:56 - mmengine - INFO - sys.platform: linux
09/19 13:33:56 - mmengine - INFO - Python: 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
09/19 13:33:56 - mmengine - INFO - CUDA available: True
09/19 13:33:56 - mmengine - INFO - numpy_random_seed: 2147483648
09/19 13:33:56 - mmengine - INFO - GPU 0,1,2,3,4,5,6: NVIDIA TITAN RTX
09/19 13:33:56 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
09/19 13:33:56 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.6, V11.6.55
09/19 13:33:56 - mmengine - INFO - GCC: x86_64-linux-gnu-gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
09/19 13:33:56 - mmengine - INFO - PyTorch: 1.13.1+cu116
09/19 13:33:56 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

09/19 13:33:56 - mmengine - INFO - TorchVision: 0.14.1+cu116
09/19 13:33:56 - mmengine - INFO - OpenCV: 4.8.0
09/19 13:33:56 - mmengine - INFO - MMEngine: 0.8.4
09/19 13:33:56 - mmengine - INFO - MMCV: 2.0.1
09/19 13:33:56 - mmengine - INFO - MMCV Compiler: GCC 9.3
09/19 13:33:56 - mmengine - INFO - MMCV CUDA Compiler: 11.6
09/19 13:33:56 - mmengine - INFO - MMDeploy: 1.2.0+
09/19 13:33:56 - mmengine - INFO - 

09/19 13:33:56 - mmengine - INFO - **********Backend information**********
09/19 13:33:56 - mmengine - INFO - tensorrt:    None
09/19 13:33:56 - mmengine - INFO - ONNXRuntime: 1.15.1
09/19 13:33:56 - mmengine - INFO - ONNXRuntime-gpu:     None
09/19 13:33:56 - mmengine - INFO - ONNXRuntime custom ops:      Available
09/19 13:33:56 - mmengine - INFO - pplnn:       None
09/19 13:33:56 - mmengine - INFO - ncnn:        None
09/19 13:33:56 - mmengine - INFO - snpe:        None
09/19 13:33:56 - mmengine - INFO - openvino:    None
09/19 13:33:56 - mmengine - INFO - torchscript: 1.13.1+cu116
09/19 13:33:56 - mmengine - INFO - torchscript custom ops:      NotAvailable
09/19 13:33:57 - mmengine - INFO - rknn-toolkit:        None
09/19 13:33:57 - mmengine - INFO - rknn-toolkit2:       None
09/19 13:33:57 - mmengine - INFO - ascend:      None
09/19 13:33:57 - mmengine - INFO - coreml:      None
09/19 13:33:57 - mmengine - INFO - tvm: None
09/19 13:33:57 - mmengine - INFO - vacc:        None
09/19 13:33:57 - mmengine - INFO - 

09/19 13:33:57 - mmengine - INFO - **********Codebase information**********
09/19 13:33:57 - mmengine - INFO - mmdet:       3.1.0
09/19 13:33:57 - mmengine - INFO - mmseg:       None
09/19 13:33:57 - mmengine - INFO - mmpretrain:  None
09/19 13:33:57 - mmengine - INFO - mmocr:       None
09/19 13:33:57 - mmengine - INFO - mmagic:      None
09/19 13:33:57 - mmengine - INFO - mmdet3d:     None
09/19 13:33:57 - mmengine - INFO - mmpose:      None
09/19 13:33:57 - mmengine - INFO - mmrotate:    None
09/19 13:33:57 - mmengine - INFO - mmaction:    None
09/19 13:33:57 - mmengine - INFO - mmrazor:     None
09/19 13:33:57 - mmengine - INFO - mmyolo:      None
```

**Comment by RunningLeon** [comment]
@chuzhixing pls. try with `main` branch. `dev-1.x` is not updated for a long time. The issue should be fixed in https://github.com/open-mmlab/mmdeploy/pull/2343

**Comment by chuzhixing** [comment]
@RunningLeon I tried the mmdeploy main branch (Git commit id=71a1e6cc>=tag1.2.0), which transformed the mmdeploy model. Using mmdeploy 1.2.0 C++SDK inference, the mask result was the same as above. Still incorrect.
Do I need to provide additional information to locate the problem?

**Comment by RunningLeon** [comment]
@chuzhixing have you rebuild the mmdeploy sdk after switch to `main` branch?

**Comment by chuzhixing** [comment]
@RunningLeon Thank you, I have rebuild the mmdeploy sdk. the mask can output normally。
![aa](https://github.com/open-mmlab/mmdeploy/assets/41979923/ec5d25eb-0b2a-48c3-9ffc-eb57581ce8f1)

```shell
[2023-09-19 15:22:04.582] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "mmdeploy_model/ins_m_dynamic"
bbox 0, left=219.71, top=176.48, right=456.85, bottom=383.84, label=13, score=0.9082
mask 0, height=427, width=640
bbox 1, left=294.31, top=116.91, right=379.05, bottom=150.32, label=2, score=0.8313
mask 1, height=427, width=640
bbox 2, left=189.66, top=108.93, right=299.74, bottom=155.32, label=2, score=0.8179
mask 2, height=427, width=640
bbox 3, left=480.42, top=111.45, right=522.94, bottom=130.64, label=2, score=0.7776
mask 3, height=427, width=640
bbox 4, left=430.47, top=105.90, right=483.40, bottom=132.46, label=2, score=0.7468
mask 4, height=427, width=640
bbox 5, left=608.96, top=112.05, right=635.03, bottom=137.98, label=2, score=0.7382
mask 5, height=427, width=640
bbox 6, left=266.36, top=105.67, right=327.27, bottom=127.71, label=2, score=0.7104
mask 6, height=427, width=640
bbox 7, left=398.12, top=111.90, right=432.66, bottom=133.47, label=2, score=0.7041
mask 7, height=427, width=640
bbox 8, left=167.67, top=109.40, right=211.07, bottom=140.76, label=2, score=0.6970
mask 8, height=427, width=640
bbox 9, left=0.09, top=111.58, right=61.66, bottom=145.99, label=2, score=0.6529
mask 9, height=427, width=640
bbox 10, left=591.90, top=110.62, right=618.56, bottom=126.70, label=2, score=0.6443
mask 10, height=427, width=640
bbox 11, left=371.68, top=134.88, right=432.91, bottom=188.73, label=13, score=0.6325
mask 11, height=427, width=640
bbox 12, left=554.93, top=110.70, right=593.33, bottom=127.70, label=2, score=0.5425
mask 12, height=427, width=640
bbox 13, left=374.70, top=111.68, right=433.23, bottom=133.64, label=2, score=0.5169
mask 13, height=427, width=640
bbox 14, left=61.73, top=94.52, right=85.42, bottom=106.42, label=2, score=0.5165
mask 14, height=427, width=640
bbox 15, left=571.04, top=110.79, right=593.48, bottom=127.51, label=2, score=0.5106
mask 15, height=427, width=640
bbox 16, left=140.26, top=96.39, right=167.16, bottom=106.19, label=2, score=0.5028
mask 16, height=427, width=640
bbox 17, left=607.04, top=112.64, right=618.91, bottom=129.54, label=2, score=0.4633
mask 17, height=427, width=640
bbox 18, left=97.99, top=89.92, right=118.95, bottom=101.28, label=2, score=0.4420
mask 18, height=427, width=640
bbox 19, left=222.08, top=98.11, right=251.52, bottom=109.15, label=2, score=0.4386
mask 19, height=427, width=640
bbox 20, left=371.19, top=134.42, right=432.78, bottom=188.59, label=56, score=0.4348
mask 20, height=427, width=640
bbox 21, left=168.19, top=96.89, right=182.86, bottom=105.61, label=2, score=0.3892
mask 21, height=427, width=640
bbox 22, left=612.68, top=102.48, right=635.09, bottom=115.17, label=2, score=0.3842
mask 22, height=427, width=640
bbox 23, left=134.16, top=91.92, right=153.50, bottom=104.48, label=2, score=0.3754
mask 23, height=427, width=640
bbox 24, left=188.70, top=109.13, right=305.44, bottom=156.18, label=7, score=0.3712
mask 24, height=427, width=640
bbox 25, left=83.88, top=90.09, right=100.96, bottom=99.65, label=2, score=0.3709
mask 25, height=427, width=640
bbox 26, left=84.12, top=90.18, right=114.90, bottom=100.53, label=2, score=0.3501
mask 26, height=427, width=640
推理时间：1726ms
```

**Comment by chuzhixing** [comment]
@RunningLeon 
Another thing is that mmdeploy 1.2 C++SDK inference for the same RTM instance m model takes longer than mmdeploy 0. x C++SDK inference.
The duration of mmdeploy 1.2 C++SDK is about 1750ms.
The duration of mmdeploy 0. x C++SDK is about 600ms.

The C++ SDK of mmdeploy version 0.x deduces that the mask result is normal in shape, but slightly smaller than the actual mask in proportion.  

The model was transformed by mmdeploy main 1.2, and the results of using mmdeploy 0.x SDK C++ for inference are as follows:  

![main1 2_mmdeploy_sdk_0 x_rtm_ins_m](https://github.com/open-mmlab/mmdeploy/assets/41979923/262cbf36-f4de-4909-aede-2e96f52d0d67)

**Comment by RunningLeon** [comment]
@chuzhixing hi
1. mmdeploy 0.x has bug for rtmdet-inst and the instance are not resized to original image shape, so it might be faster.
2. mmdeploy 1.x fixed the bug and do the mask resizing on cpu using opencv, which could be slower.
https://github.com/open-mmlab/mmdeploy/blob/71a1e6cc1859d8692cea134946bdc249ad0e5400/csrc/mmdeploy/codebase/mmdet/instance_segmentation.cpp#L142-L163

**Comment by chuzhixing** [comment]
@RunningLeon 

Hello, here is my hardware and software information.  
OS: Windows 10  
CPU: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz 3.00 GHz  
RAM: 16.0 GB  
Onnx runtime: onnxruntime-win-x64-1.8.1  
mmdeploy: 1.2.0  
model：RTMDet instance m  
img: /mmdetection/demo/demo.jpg  (640*427*3)  

Is it reasonable for the mmdeploy 1.2.0 C++ SDK for this model to have an inference time of over 1700ms in the above environment?   

Can some of my software environments be configured incorrectly?
