### ISSUE TITLE
A bug in c# sdk demo maybe

### ISSUE THREAD

**Issue by jrChen2022a** [open-mmlab/mmdeploy#613]
When running mmdeploy/demo/csharp/Demo.sln in VS2019 in windows11，an error, 
'System.AccessViolationException:“Attempted to read or write protected memory. This is often an indication that other memory is corrupt.” '
, sometimes occurrs in line 52, 
'List<DetectorOutput> output = handle.Apply(mats);'.
Like:
<img width="699" alt="mmexport1655459458335" src="https://user-images.githubusercontent.com/100680047/174274526-0f00d488-472a-4200-b4da-c46b91fec527.png">

**Comment by jrChen2022a** [comment]
sorry, wrong picture

**Comment by caj-github** [comment]
same problem in win10
[2022-06-19 10:45:49.924] [mmdeploy] [warning] [bulk.h:39] fallback Bulk implementation
[2022-06-19 10:45:49.933] [mmdeploy] [warning] [bulk.h:39] fallback Bulk implementation
[2022-06-19 10:45:50.574] [mmdeploy] [warning] [bulk.h:39] fallback Bulk implementation
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at MMDeploy.NativeMethods.mmdeploy_detector_release_result(MMDeploy.CDetect*, Int32*, Int32)
   at MMDeploy.NativeMethods.mmdeploy_detector_release_result(MMDeploy.CDetect*, Int32*, Int32)
   at MMDeploy.Detector.ReleaseResult(MMDeploy.CDetect*, Int32*, Int32)
   at MMDeploy.Detector.Apply(MMDeploy.Mat[])
   at object_detection.Program.Main(System.String[])

**Comment by caj-github** [comment]
i changed source code, it works now

first change in mmdeploy\csrc\mmdeploy\backend_ops\tensorrt\multi_level_roi_align.cpp\trt_multi_level_roi_align.cpp

![image](https://user-images.githubusercontent.com/55951697/174470466-656b86cf-e90e-468d-8428-cc13092775be.png)

second change in mmdeploy\csrc\mmdeploy\apis\csharp\MMDeploy\APIs\Detector.cs
![image](https://user-images.githubusercontent.com/55951697/174470592-8a015df7-a563-410f-9697-c71d4633e05a.png)

**Comment by irexyc** [comment]
The `total` args passed to ReleaseResult is wrong. 
https://github.com/open-mmlab/mmdeploy/pull/620/files

Should be fixed after pr620

**Comment by jrChen2022a** [comment]
> The `total` args passed to ReleaseResult is wrong. https://github.com/open-mmlab/mmdeploy/pull/620/files
> 
> Should be fixed after pr620

**Comment by jrChen2022a** [comment]
> i changed source code, it works now
> 
> first change in mmdeploy\csrc\mmdeploy\backend_ops\tensorrt\multi_level_roi_align.cpp\trt_multi_level_roi_align.cpp
> 
> ![image](https://user-images.githubusercontent.com/55951697/174470466-656b86cf-e90e-468d-8428-cc13092775be.png)
> 
> second change in mmdeploy\csrc\mmdeploy\apis\csharp\MMDeploy\APIs\Detector.cs ![image](https://user-images.githubusercontent.com/55951697/174470592-8a015df7-a563-410f-9697-c71d4633e05a.png)

It works. Thank you so much!!!

**Comment by jrChen2022a** [comment]
> The `total` args passed to ReleaseResult is wrong. https://github.com/open-mmlab/mmdeploy/pull/620/files
> 
> Should be fixed after pr620

Thanks for your reply. Unfortunately, the problem still exists.

**Comment by irexyc** [comment]
Have you regenerate and reinstall the nuget package?

It's better to generate nuget package with different version. If you generate the package with the same version, the installation will install the cached one. 
So if you previous generate the package with command ```dotnet build --configuration Release -p:Version=0.5.0```, it's better to use ```dotnet build --configuration Release -p:Version=0.5.1``` after you update the code
